### ISSUE TITLE
Updating all dependencies to the vision module of 9.4.0

### ISSUE THREAD

**Issue by tatocaster** [EdwardvanRaak/MaterialBarcodeScanner#26]
update 8.4.0 to `com.google.android.gms:play-services-vision:9.4.0` please

**Comment by navidemad** [comment]
👍  It will may be patch this error with also the merging of [PR/Fix possible NullPointerException](https://github.com/EdwardvanRaak/MaterialBarcodeScanner/pull/22).

From [**CameraSource.java:1175**](https://github.com/EdwardvanRaak/MaterialBarcodeScanner/blob/master/materialbarcodescanner/src/main/java/com/edwardvanraak/materialbarcodescanner/CameraSource.java#L1176)
**E/OpenCameraSource: Exception thrown from receiver.**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.vision.Detector.receiveFrame(com.google.android.gms.vision.Frame)' on a null object reference
     at com.edwardvanraak.materialbarcodescanner.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1175)
     at java.lang.Thread.run(Thread.java:818)
```
