### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by vanlooverenkoen** [EdwardvanRaak/MaterialBarcodeScanner#32]
I Get this error after adding this: 

```
        final MaterialBarcodeScanner materialBarcodeScanner = new MaterialBarcodeScannerBuilder()
                .withActivity(SettingsActivity.this)
                .withEnableAutoFocus(true)
                .withBleepEnabled(true)
                .withBackfacingCamera()
                .withText("Scanning...")
                .withResultListener(new MaterialBarcodeScanner.OnResultListener() {
                    @Override
                    public void onResult(Barcode barcode) {
                        midiMacroIpTv.setText(barcode.rawValue);
                    }
                })
                .build();
        materialBarcodeScanner.startScan();
```

In my manifest I added the camera permissions

```
Process: be.vanlooverenkoen.midimacro.dev, PID: 7079
                                                                                java.lang.NoSuchMethodError: No static method zzC(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/data/be.vanlooverenkoen.midimacro.dev/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-10.0.1_04ea9d2af81f21a7139774c35bc30f5adcb908d3-classes.dex)
                                                                                    at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zzb(Unknown Source)
                                                                                    at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zza(Unknown Source)
                                                                                    at com.google.android.gms.vision.barcode.internal.client.zzd.zzIg(Unknown Source)
                                                                                    at com.google.android.gms.vision.barcode.internal.client.zzd.<init>(Unknown Source)
                                                                                    at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
                                                                                    at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerBuilder.buildMobileVisionBarcodeDetector(MaterialBarcodeScannerBuilder.java:237)
                                                                                    at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerBuilder.build(MaterialBarcodeScannerBuilder.java:221)
                                                                                    at be.vanlooverenkoen.midimacro.ui.SettingsActivity.onClickConfigureMidiMacroServer(SettingsActivity.java:184)
                                                                                    at be.vanlooverenkoen.midimacro.ui.SettingsActivity_ViewBinding$1.doClick(SettingsActivity_ViewBinding.java:44)
                                                                                    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                    at android.view.View.performClick(View.java:5637)
                                                                                    at android.view.View$PerformClick.run(View.java:22429)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by pqtuan86** [comment]
Same here! Any solution for this issue?

**Comment by vinayAnna** [comment]
facing similar issue.. any resolution for this?
