### ISSUE TITLE
EventBus: Could not dispatch event

### ISSUE THREAD

**Issue by Axrorxoja** [EdwardvanRaak/MaterialBarcodeScanner#38]
Hi, Thank you for usefull lib, I use it in fragment.
It's fragment function
 public void onResult(Barcode barcode)
            {
                ........................................
                EventBus bus = EventBus.getDefault();
                bus.removeAllStickyEvents();
                bus.removeStickyEvent(materialBarcodeScanner);
                bus.removeStickyEvent(getActivity());
                if (bus.isRegistered(materialBarcodeScanner))
                    bus.unregister(materialBarcodeScanner);
                materialBarcodeScanner = null;
                listener.onQRScanFinished();
            }
And i from fragment call activity function via listener.onQRScanFinished();
It's activity function
  @Override
        public void onQRScanFinished()
            {
                getSupportFragmentManager().popBackStack();
                Timber.d("onQRScanFinished");
            }
after that Event bus say 
`Could not dispatch event: class com.google.android.gms.vision.barcode.Barcode to subscribing class class com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScanner
                                                                   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                                       at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:770)
                                                                       at uz.uzgps.android.viewer.screens.login.LoginActivity.removeLastFragment(LoginActivity.java:125)
                                                                       at uz.uzgps.android.viewer.screens.login.LoginActivity.onQRScanFinished(LoginActivity.java:119)
                                                                       at uz.uzgps.android.viewer.screens.login.fragments.QReaderFragment.onResult(QReaderFragment.java:135)`

**Comment by ratanakpek** [comment]
I am error with it too

**Comment by bpappin** [comment]
+1

**Comment by bpappin** [comment]
see #34 and #35
