### ISSUE TITLE
error when start scanning

### ISSUE THREAD

**Issue by rijudewan** [EdwardvanRaak/MaterialBarcodeScanner#39]
hi
can you tell what is causing this error 
java.lang.NoSuchMethodError: No static method zzC(Ljava/lang/Object;)Lcom/google/android/gms/dynamic/zzd; in class Lcom/google/android/gms/dynamic/zze; or its super classes (declaration of 'com.google.android.gms.dynamic.zze' appears in /data/app/com.richard.myvansales-2/split_lib_dependencies_apk.apk:classes18.dex)
                                                                          at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zzb(Unknown Source)
                                                                          at com.google.android.gms.vision.barcode.internal.client.zzd$zza.zza(Unknown Source)
                                                                          at com.google.android.gms.vision.barcode.internal.client.zzd.zzIg(Unknown Source)
                                                                          at com.google.android.gms.vision.barcode.internal.client.zzd.<init>(Unknown Source)
                                                                          at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)
                                                                          at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerBuilder.buildMobileVisionBarcodeDetector(MaterialBarcodeScannerBuilder.java:237)
                                                                          at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerBuilder.build(MaterialBarcodeScannerBuilder.java:221)
                                                                          at com.richard.myvansales.cashsales.CashSales.startScan(CashSales.java:1889)
                                                                          at com.richard.myvansales.cashsales.CashSales.access$000(CashSales.java:90)
                                                                          at com.richard.myvansales.cashsales.CashSales$8.onClick(CashSales.java:498)
                                                                          at android.view.View.performClick(View.java:5226)
                                                                          at android.view.View$PerformClick.run(View.java:21266)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:168)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by deepakbms** [comment]
Hey Try to add this    

 compile 'com.android.support:appcompat-v7:~~Your Version~~
    compile 'com.google.android.gms:play-services-basement:~~Your Version~~
    compile 'com.google.android.gms:play-services-vision:~~Your Version~~
    compile 'com.android.support:design:~~Your Version~~
    compile 'com.android.support:support-annotations:~~Your Version~~

**Comment by tejas4888** [comment]
I got a similar error...
It was because I added google services latest version plugin that caused the BarcodeScanner to crash
I then reverted all google play service dependencies to a previous version i.e. from 10.0.1 to 9.0.0

Advise : Try to add google vision dependency always, to use this scanner

My build.gradle(before)
compile 'com.google.firebase:firebase-database10.0.1'
compile 'com.google.firebase:firebase-messaging:10.0.1'
compile 'com.google.android.gms:play-services-vision:10.0.1'

My build.gradle (after)
compile 'com.google.firebase:firebase-database:9.0.0'
compile 'com.google.firebase:firebase-messaging:9.0.0'
compile 'com.google.android.gms:play-services-vision:9.0.0'

Now it works fine...
