### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException - Device xiaomi-1s ( 4.2.2) 

### ISSUE THREAD

**Issue by Piashsarker** [EdwardvanRaak/MaterialBarcodeScanner#50]
```
Fatal Exception: java.lang.NullPointerException
       at com.edwardvanraak.materialbarcodescanner.CameraSource.setFlashMode(CameraSource.java:557)
       at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerActivity.enableTorch(MaterialBarcodeScannerActivity.java:176)
       at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerActivity.access$300(MaterialBarcodeScannerActivity.java:28)
       at com.edwardvanraak.materialbarcodescanner.MaterialBarcodeScannerActivity$2.onClick(MaterialBarcodeScannerActivity.java:115)
       at android.view.View.performClick(View.java:4204)
       at android.view.View.performAccessibilityActionInternal(View.java:6919)
       at android.view.View.performAccessibilityAction(View.java:6906)
       at android.view.AccessibilityInteractionController.perfromAccessibilityActionUiThread(AccessibilityInteractionController.java:550)
       at android.view.AccessibilityInteractionController.access$300(AccessibilityInteractionController.java:48)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:887)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5042)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at de.robv.android.xp0sed.Xp0sedBridge.main(Xp0sedBridge.java:117)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by bpappin** [comment]
#54 duplicates this bug.

**Comment by bpappin** [comment]
This may have been fixed in Pull Request #29
