### ISSUE TITLE
Crashes when forcing landscape 

### ISSUE THREAD

**Issue by kenticus** [EdwardvanRaak/MaterialBarcodeScanner#7]
`java.lang.RuntimeException: set display orientation failed
                                                                                     at android.hardware.Camera.setDisplayOrientation(Native Method)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSource.setRotation(CameraSource.java:993)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSource.createCamera(CameraSource.java:750)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSource.start(CameraSource.java:357)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSourcePreview.startIfReady(CameraSourcePreview.java:89)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSourcePreview.access$200(CameraSourcePreview.java:32)
                                                                                     at com.edwardvanraak.materialbarcodescanner.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:112)
                                                                                     at android.view.SurfaceView.updateWindow(SurfaceView.java:710)
                                                                                     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:208)
                                                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
                                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2326)
                                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1313)
                                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7055)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

**Comment by EdwardvanRaak** [comment]
I need some more information if possible. 

What exactly are you doing to "force" landscape mode? Also on what API and device is this happening?

**Comment by kenticus** [comment]
I'm assuming its because i have my activity in landscape mode.
`        <activity
            android:name=".activities.ScanActivity"
            android:screenOrientation="landscape" />`

I'm running it on Android sdk 22 using the front facing camera

**Comment by kenticus** [comment]
Also, I'm using the Galaxy View. It's a massive 18 inch device that I'm going to use as a kiosk.

**Comment by EdwardvanRaak** [comment]
Interesting.

So far I was unable to reproduce the crash on an emulator or phone with a normal size screen. Are you able to test your app on an emulator or phone as well? Because then I would at least know if the giant screen is part of the problem.
